name: 1. Release new version

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-release.yml
    with:
      source_branch: develop
      dest_branch: main
      release_type: ${{ inputs.release_type }}
