name: 2. Release To Production

on:
  workflow_call:

jobs:
  merge:
    name: Merge
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
          # token: ${{ secrets.MDSBD_MAVEN_PASSWORD }}
      - name: Merge test into main
        run: git merge origin/test && git push origin main
