name: Release

on:
  workflow_dispatch:
    branches: master
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: develop
          # token: ${{ secrets.MDSBD_MAVEN_PASSWORD }}
      - name: Setup pnPM 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: https://npm.pkg.github.com
          scope: mds-bd
      - name: Install Dependencies
        run: pnpm install
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.MDSBD_MAVEN_PASSWORD }} # required for @mds-bd
      - name: Bump version without commit
        run: pnpm version minor --no-git-tag-version
      - name: Build
        run: pnpm build
      - name: Commit Bump version and Build
        run: git add . && git commit -m "🚀 bump version + 📦️ build files"
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: test
          # token: ${{ secrets.MDSBD_MAVEN_PASSWORD }}
      - name: Merge develop into test
        run: git merge develop
