name: 4. Reusable Release (CANNOT BE USED DIRECTLY)

on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
        default: "develop"
      dest_branch:
        required: true
        type: string
        default: "test"
env:
  AUTHOR_BOT_NAME: Bot GitHub Actions

jobs:
  build:
    name: Bump version, build and merge ${{ inputs.source_branch }} into ${{ inputs.dest_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo with fetching all branches history
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.source_branch }}
          fetch-depth: 0 # fetch all history for all branches and tags
          # token: ${{ secrets.MDSBD_MAVEN_PASSWORD }}
      - name: Setup git user
        run: git config --global user.email "<>" && git config --global user.name "$AUTHOR_BOT_NAME"
      - name: Setup pnPM 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: https://npm.pkg.github.com
          # scope: mds-bd
      - name: Install Dependencies
        run: pnpm install
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.MDSBD_MAVEN_PASSWORD }} # required for @mds-bd
      - name: Bump version without commit
        run: pnpm version minor --no-git-tag-version
      - name: Build
        run: pnpm build
      - name: Commit Bump version and Build
        run: git add . && git commit -m "🚀 bump version + 📦️ build files"
      - name: push ${{ inputs.source_branch }}
        run: git push origin ${{ inputs.source_branch }}
      # - name: Checkout Repo
      # uses: actions/checkout@v3
      # with:
      # ref: ${{ inputs.dest_branch }}
      # token: ${{ secrets.MDSBD_MAVEN_PASSWORD }}
      - name: Checkout ${{ inputs.dest_branch }}
        run: git checkout ${{ inputs.dest_branch }}
      - name: Merge ${{ inputs.source_branch }} into ${{ inputs.dest_branch }}
        run: git merge origin/${{ inputs.source_branch }}
      - name: push ${{ inputs.dest_branch }}
        run: git push origin ${{ inputs.dest_branch }}
